name: open-unmix-pytorch-osx

channels:
  - conda-forge
  - pytorch

dependencies:
  - python==3.7.1
  - numpy==1.15.4
  - pytorch>=1.0.1
  - torchvision==0.2.2
  - pescador==2.0.0
  - tqdm==4.28.1
  - pip:
    - git+https://github.com/sigsep/sigsep-mus-db.git@v3#egg=musdb
    - git+https://github.com/sigsep/norbert#egg=norbert