name: open-unmix-pytorch-gpu

channels:
  - conda-forge
  - pytorch

dependencies:
  - python==3.6.5
  - numpy==1.15.4
  - pytorch>=0.4.1
  - torchvision==0.2.1
  - cuda92
  - pescador==2.0.0
  - tqdm==4.28.1
  - pip:
    - norbert>=0.1.0
    - musdb>=0.3.0
