name: open-unmix-pytorch-osx

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - numpy=1.15
  - pytorch=1.1.0
  - tqdm=4.28
  - scikit-learn=0.21
  - ffmpeg
  - resampy
  - pip
  - pip:
    - musdb==0.3.0.post1
    - norbert==0.2.0