name: open-unmix-pytorch-linux-cpu

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - numpy=1.18
  - scipy=1.4
  - pytorch=1.5.0
  - cpuonly
  - torchaudio=0.5.0
  - tqdm
  - scikit-learn=0.22
  - ffmpeg
  - resampy
  - pip
  - pip:
    - musdb==0.3.1
    - norbert>=0.2.0
    - museval==0.3.0
    - gitpython