name: open-unmix-pytorch-osx

channels:
  - conda-forge
  - pytorch

dependencies:
  - python==3.7.1
  - numpy==1.15.4
  - pytorch>=1.1.0
  - tqdm==4.28.1
  - scikit-learn==0.21.2
  - ffmpeg
  - resampy
  - pip:
    - musdb==0.3.0.post1
    - norbert==0.2.0