name: open-unmix-pytorch-osx

channels:
  - conda-forge
  - pytorch

dependencies:
  - python==3.7.1
  - numpy==1.15.4
  - pytorch>=1.1.0
  - pescador==2.0.0
  - tqdm==4.28.1
  - musdb==0.3.0
  - ffmpeg
  - resampy
  - pip:
    - git+https://github.com/sigsep/norbert#egg=norbert